/**
 *  @file       versioning.js
 *  @brief      The Versioning module of the App.
 *  @author     Yiwei Chiao (ywchiao@gmail.com)
 *  @date       08/17/2017 created.
 *  @date       03/19/2018 last modified.
 *  @version    0.4.0
 *  @since      0.1.0
 *  @copyright  MIT, © 2017-2018 Yiwei Chiao
 *  @details
 *
 *  The Versioning module of the App.
 */
'use strict';

const created = '03/19/2018';
const since = '0.1.0';

const ver = {
  'name': null,
  'version': null,
  'description': null,
  'author': null,
  'email': 'ywchiao@gmail.com',
  'license': null,
};

let capitalizeFirstLetter = (str) => {
  return str.charAt(0).toUpperCase() + str.slice(1);
};

let prefix = (ver) => {
  let today = (new Date()).toISOString();
  let year = today.slice(0, 4);
  let month = today.slice(5, 7);
  let day = today.slice(8, 10);

  if (ver.copyright != year) {
    ver.copyright = `${ver.copyright}-${year}`;
  }
  else {
    ver.copyright = `${ver.copyright}`;
  }

  ver['built'] = `${month}/${day}/${year}`;

  return `\/**
*  @file       version.js
*  @brief      The Version information module of the ${ver.name}.
*  @author     ${ver.author} (${ver.email})
*  @date       ${created} created.
*  @date       ${ver.built} last modified.
*  @version    ${ver.version}
*  @since      ${since}
*  @copyright  ${ver.license}, © ${ver.copyright} ${ver.author.name}
*  @details
* 
*  The Version information module of the ${ver.name}.
*
*  This file is automatically generated. DONOT edit it by hand.
**\/
'use strict';

export const ABOUT = `;
};

const postfix = ';\n\n\/\/ about\/version.js\n';

/**
 * Pull the version information from Package.json into 
 * './src/about/version.js' for building the web application's 
 * version report functionality.
 *
 * @version 0.1.0
 * @since 0.1.0
 * @returns {undefined}
 */
(() => {
  let fs = require('fs');

  let pkg = require('./package.json');
  let output = './src/about/version.js';

  Object.keys(ver).forEach(key => {
    ver[key] = pkg[key];
  });

  ver['name'] = capitalizeFirstLetter(ver['name']);
  ver['copyright'] = created.slice(6, 10);

  fs.writeFile(
    output,
    prefix(ver) + JSON.stringify(ver, null, '  ') + postfix,
    (err) => {
      if (err) {
        return console.log(err);
      } // fi
      else {
        return console.log(
          'Project [' + ver['name'] + '] versioned as: ' + ver['version']
        );
      } // esle
    }
  );
})();

// versioning.js
