/**
*  @file       version.js
*  @brief      The Version information module of the Amaze.
*  @author     Yiwei Chiao (undefined)
*  @date       03/19/2018 created.
*  @date       11/04/2021 last modified.
*  @version    0.1.0-build.10
*  @since      0.1.0
*  @copyright  MIT, © 2018-2021 undefined
*  @details
* 
*  The Version information module of the Amaze.
*
*  This file is automatically generated. DONOT edit it by hand.
**/
'use strict';

export const ABOUT = {
  "name": "Amaze",
  "version": "0.1.0-build.10",
  "description": "A man's",
  "author": "Yiwei Chiao",
  "license": "MIT",
  "copyright": "2018-2021",
  "built": "11/04/2021"
};

// about/version.js
